#!/usr/bin/env python3
"""Export ORM schema to SQL file."""

import sys
from pathlib import Path

# Add src to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))

from sqlalchemy.schema import CreateTable, CreateIndex

from ai_platform.domain.models import Base


def export_schema() -> None:
    """Generate SQL DDL from ORM models."""
    sql_statements = []

    # Header
    sql_statements.append("-- =============================================================================")
    sql_statements.append("-- AI Platform - Current ORM Schema")
    sql_statements.append("-- Generated by: make schema-export")
    sql_statements.append("-- =============================================================================")
    sql_statements.append("")

    # Generate CREATE TABLE statements
    for table_name in sorted(Base.metadata.tables.keys()):
        table = Base.metadata.tables[table_name]
        sql_statements.append(f"-- Table: {table_name}")
        create_stmt = str(CreateTable(table).compile(compile_kwargs={"literal_binds": True})).strip()
        sql_statements.append(create_stmt + ";")
        sql_statements.append("")

        # Generate indexes
        for index in table.indexes:
            idx_stmt = str(CreateIndex(index).compile(compile_kwargs={"literal_binds": True})).strip()
            sql_statements.append(idx_stmt + ";")
            sql_statements.append("")

    # Write to file
    output_path = Path(__file__).parent.parent / "docs" / "sql" / "current_orm_schema.sql"
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_statements))

    print(f"Exported {len(Base.metadata.tables)} tables to: {output_path}")


if __name__ == "__main__":
    export_schema()
